"""empty message

Revision ID: e4e4ed639753
Revises: 
Create Date: 2023-03-12 10:01:12.439814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e4ed639753'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('property_type', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('price', sa.String(length=15), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bedrooms', sa.String(length=3), nullable=True),
    sa.Column('bathrooms', sa.String(length=3), nullable=True),
    sa.Column('photo_filename', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
